services:

  - id: jellyfin
    host: asset-002
    port: 8096
    type: media-server

  - id: tdarr
    host: asset-002
    port: 8265
    type: transcoder

  - id: portainer
    host: asset-002
    port: 9000
    type: docker-management

  - id: uptime-kuma
    host: asset-002
    port: 3001
    type: monitoring
