services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265  # Web UI
      - 8266:8266  # Server port
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - internalNode=true
      - nodeName=MyInternalNode
    volumes:
      - /your/config/tdarr:/app/configs
      - /your/config/tdarr/server:/app/server
      - /your/config/tdarr/logs:/app/logs
      - /srv/media:/media  # your actual media path
      - /tmp/tdarr:/temp
